function createfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 23-Jul-2020 10:10:40

% Create figure
figure('OuterPosition',[612.2 302.6 574.4 423.2]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Cryptocurrencies','MarkerSize',14,'Marker','.',...
    'LineStyle','none',...
    'Color',[0 1 0]);

% Create plot
plot(X2,Y2,'DisplayName','Commodities','MarkerSize',14,'Marker','.',...
    'LineStyle','none');

% Create plot
plot(X3,Y3,'DisplayName','Exchange rates','MarkerSize',14,'Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X4,Y4,'DisplayName','Stocks','MarkerSize',14,'Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 0]);

box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.617023806935266 0.148181464147443 0.253928575311388 0.208333337907311]);

